name: Test

on: 
  pull_request: {}
  push:
    branches: main
    tags: "*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5                       # Downloads python, adds it to the path. Sets up pip too.
        with:
          python-version: "3.12.13"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies 
        run: poetry install --with dev

      - run: poetry run pytest --cov=python_repo_template --cov-report=json --cov-fail-under=90

      - name: Extract coverage
        run: |
          COVERAGE=$(python -c "import json; print(round(json.load(open('coverage.json'))['totals']['percent_covered']))")
          echo "COVERAGE=$COVERAGE" >> $GITHUB_ENV

      - name: Update coverage badge Gist
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gistID: 72baafb92457db7916a1014ae5dd3d40
          filename: coverage.json
          label: Coverage
          message: ${{ env.COVERAGE }}%
          color: green